import { redirect } from "next/navigation";
import { AdminNav } from "@/components/AdminNav";
import { requireAdmin } from "@/lib/admin-verify";
import { requireSupabaseServiceClient } from "@/lib/supabase/service";
import { countActiveGrantsByMarina, formatJoinCode } from "@/lib/marina-access";
import { CreateMarinaForm, MarinaAdminCard, type AdminMarina } from "./MarinaAdminForms";

/**
 * Marina accounts: create one and issue its code in one pass (done on a
 * phone in the marina's office), reissue a code, and attach or remove
 * staff. docs/moxie_digital_marina_access_spec.md §5.1–5.2.
 *
 * The create form is first on the page for that reason. The poster is not
 * made here — it's a print file, generated by `npm run marina-poster`.
 */
export default async function AdminMarinasPage() {
  const admin = await requireAdmin();
  if (!admin) redirect("/dashboard");

  const service = requireSupabaseServiceClient("app/admin/marinas/page");
  const [{ data: marinaRows, error }, { data: staffRows, error: staffError }, grantCounts] = await Promise.all([
    service.from("marinas").select("id, name, city, state, join_code, created_at").order("created_at", { ascending: false }),
    service.from("users").select("id, email, marina_id").not("marina_id", "is", null),
    countActiveGrantsByMarina(service),
  ]);
  if (error) throw new Error(`Failed to load marinas: ${error.message}`);
  if (staffError) throw new Error(`Failed to load marina staff: ${staffError.message}`);

  const staff = (staffRows ?? []) as { id: string; email: string; marina_id: string }[];
  const marinas: AdminMarina[] = (
    (marinaRows ?? []) as { id: string; name: string; city: string | null; state: string | null; join_code: string | null }[]
  ).map((m) => ({
    id: m.id,
    name: m.name,
    place: [m.city, m.state].filter(Boolean).join(", ") || null,
    code: m.join_code ? formatJoinCode(m.join_code) : null,
    vessels: grantCounts.get(m.id) ?? 0,
    staff: staff.filter((u) => u.marina_id === m.id).map((u) => ({ id: u.id, email: u.email })),
  }));

  return (
    <div className="min-h-screen bg-[var(--cream)] px-4 py-8 sm:px-8">
      <main className="mx-auto w-full max-w-2xl">
        <AdminNav current="/admin/marinas" />
        <header className="mb-5">
          <p className="font-[family-name:var(--font-dm)] text-xs font-medium uppercase tracking-[0.12em] text-[var(--text3)]">Admin</p>
          <h1 className="mt-1 font-[family-name:var(--font-display)] text-3xl font-light italic text-[var(--navy)]">Marinas</h1>
        </header>

        <CreateMarinaForm />

        <h2 className="mb-2 mt-8 font-[family-name:var(--font-dm)] text-xs font-medium uppercase tracking-[0.12em] text-[var(--text3)]">
          {marinas.length} marina{marinas.length === 1 ? "" : "s"}
        </h2>
        <div className="space-y-3">
          {marinas.map((m) => (
            <MarinaAdminCard key={m.id} marina={m} />
          ))}
        </div>

        <p className="mt-8 font-[family-name:var(--font-dm)] text-xs text-[var(--text2)]">
          Poster: run <code className="rounded bg-[var(--cream2)] px-1">npm run marina-poster -- &lt;CODE&gt;</code> in{" "}
          <code className="rounded bg-[var(--cream2)] px-1">web/</code> for a print-ready PDF.
        </p>
      </main>
    </div>
  );
}
