-- Moxie Digital: the mint operation's transactional half.
--
-- Stage 3 of docs/moxie_digital_badge_provisioning_spec.md — §5.0.2
-- steps 1-4. Artwork (steps 5-7) is stage 4 and is deliberately not here.
--
-- WHY THIS IS A FUNCTION AND NOT THREE CLIENT CALLS
--
-- §5.0.2 requires steps 1-4 to be one transaction. PostgREST has no
-- multi-statement transaction, so issuing them from the app would leave
-- windows where a batch row exists with no identities, or identities
-- exist with MXE IDs and no batch. A plpgsql function is the only way to
-- get the boundary the spec asks for.
--
-- WHY THE BATCH ROW IS INSERTED FIRST (§5.0.1)
--
-- The UNIQUE constraint on label IS the double-submission guard. Insert
-- it first and a double-clicked or retried mint aborts on that
-- constraint having called next_mxe_id() zero times — nothing consumed.
-- Written the intuitive way round (allocate IDs, then record the batch)
-- every accidental double-click would burn 100 sequence values. Gaps in
-- mxe_id_seq are acceptable (20260904 says so explicitly) but they
-- should be caused by real events, not by an impatient click on a slow
-- connection.
--
-- Tokens are generated in the application (web/src/lib/badge-token.ts)
-- and passed in, rather than generated here. That keeps one
-- implementation of the Crockford alphabet and the unbiased sampling,
-- and keeps it unit-testable. If a token collides between the
-- application's uniqueness check and this insert, the UNIQUE constraint
-- aborts the whole transaction — no partial batch, and the caller
-- retries.

BEGIN;

CREATE OR REPLACE FUNCTION public.mint_badge_batch(
  p_label               TEXT,
  p_count               INTEGER,
  p_copies_per_identity SMALLINT,
  p_qr_version          SMALLINT,
  p_tokens              TEXT[]
)
RETURNS UUID
LANGUAGE plpgsql
AS $$
DECLARE
  v_batch_id UUID;
  v_mxe_id   TEXT;
  i          INTEGER;
BEGIN
  IF p_count IS NULL OR p_count < 1 THEN
    RAISE EXCEPTION 'mint_badge_batch: count must be a positive integer, got %', p_count;
  END IF;

  IF p_tokens IS NULL OR array_length(p_tokens, 1) IS DISTINCT FROM p_count THEN
    RAISE EXCEPTION 'mint_badge_batch: expected % tokens, got %',
      p_count, COALESCE(array_length(p_tokens, 1), 0);
  END IF;

  -- Cheap pre-check for duplicates inside the array itself. The UNIQUE
  -- index would catch it anyway, but this fails with a message that says
  -- what actually went wrong rather than a constraint name.
  IF (SELECT count(DISTINCT t) FROM unnest(p_tokens) AS t) <> p_count THEN
    RAISE EXCEPTION 'mint_badge_batch: token list contains duplicates';
  END IF;

  -- ── STEP 1 — the guard. Before anything is consumed. ──────────────
  INSERT INTO public.badge_print_batches (label, minted_count, copies_per_identity, qr_version)
  VALUES (p_label, p_count, p_copies_per_identity, p_qr_version)
  RETURNING id INTO v_batch_id;

  -- ── STEPS 2-4 — allocate an MXE ID per identity and insert. ───────
  -- One next_mxe_id() call per row, in order, so a batch occupies a
  -- contiguous ID range and the shelf can be worked front to back
  -- (the assignment query in §3.1 orders by mxe_id for the same reason).
  FOR i IN 1..p_count LOOP
    v_mxe_id := public.next_mxe_id();

    INSERT INTO public.badge_identities (mxe_id, token, status, print_batch_id, artwork_path)
    VALUES (v_mxe_id, p_tokens[i], 'minted', v_batch_id, NULL);
  END LOOP;

  RETURN v_batch_id;
END $$;

COMMENT ON FUNCTION public.mint_badge_batch(TEXT, INTEGER, SMALLINT, SMALLINT, TEXT[]) IS
  'Atomically mints a batch of badge identities: batch row first (the UNIQUE label is the double-submission guard), then one next_mxe_id() and one badge_identities row per identity, all at status=''minted'' with artwork_path NULL. Artwork is rendered separately and resumably — see spec §5.0.2 steps 5-7. Tokens are generated by the application and passed in.';

COMMIT;

-- ────────────────────────────────────────────────────────────────────────────
-- Verify after running:
--
--   -- exists, with the right signature
--   SELECT proname, pg_get_function_arguments(oid)
--     FROM pg_proc WHERE proname = 'mint_badge_batch';
--
--   -- the label constraint, tested WITHOUT burning any MXE IDs
--   -- (this touches only badge_print_batches, so next_mxe_id() is never
--   -- reached, and the ROLLBACK leaves no trace):
--   BEGIN;
--     INSERT INTO badge_print_batches (label, minted_count, copies_per_identity, qr_version)
--       VALUES ('guard-test', 2, 2, 4);
--     INSERT INTO badge_print_batches (label, minted_count, copies_per_identity, qr_version)
--       VALUES ('guard-test', 2, 2, 4);   -- must ERROR on badge_print_batches_label_key
--   ROLLBACK;
--
-- The end-to-end guard is better tested through /admin/badges: mint a
-- small batch, then submit the same label again. The second attempt must
-- report the label collision, and
--
--   SELECT last_value FROM mxe_id_seq;
--
-- must read the same before and after that failed attempt — because the
-- batch insert is the first statement in this function, so a duplicate
-- label aborts before next_mxe_id() is ever called.
--
-- NOTE: a SUCCESSFUL mint does consume IDs permanently, including if the
-- surrounding transaction later rolls back. nextval() does not roll back
-- by design (20260904_mxe_id_sequence.sql explains why). Test mints burn
-- real MXE IDs; that is expected and the gaps are harmless.
-- ────────────────────────────────────────────────────────────────────────────
